apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: demo-installation
  namespace: demo-namespace
  annotations:
    landscaper.gardener.cloud/operation: reconcile
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: [your-base-url]
      componentName: github.com/gardener/landscapercli/examplecontainer
      version: v0.1.0

  blueprint:
    ref:
      resourceName: blueprint

  imports:
    targets:
      - name: target-cluster
        # the "#" forces the landscaper to use the target with the name "rg-cluster" in the same namespace
        target: "#your-cluster"

  exports:
    data:
      - name: sentence
        dataRef: "sentence-do"

  importDataMappings:
    word: word1
    sleepTimeBefore: 300
    sleepTimeAfter: 300
