apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: demo-installation
  namespace: demo-namespace
spec:
  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: [your-base-url]
      componentName: github.com/gardener/landscapercli/examplecontainer
      version: v0.1.0

  blueprint:
    ref:
      resourceName: blueprint

  importDataMappings:
    word: word1
    sleepTimeBefore: 300
    sleepTimeAfter: 300
