apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- default:
    value: null
  name: target-cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster
- default:
    value: null
  name: nginx-namespace
  required: true
  schema:
    type: string

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-execution-nginx.yaml
  name: nginx
  type: GoTemplate
