apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- default:
    value: null
  name: target-cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster
- default:
    value: null
  name: word
  required: true
  schema:
    type: string
- default:
    value: null
  name: sleepTimeBefore
  required: true
  schema:
    type: integer
- default:
    value: null
  name: sleepTimeAfter
  required: true
  schema:
    type: integer

exports:
- name: sentence
  schema:
    type: string

exportExecutions:
- name: examplecontainer
  template: |
    exports:
      sentence: {{ index .values "deployitems" "examplecontainer" "sentence" }}
  type: GoTemplate

subinstallations: []

deployExecutions:
- file: /deploy-execution-examplecontainer.yaml
  name: examplecontainer
  type: GoTemplate
