deployItems:
  - name: ingress-nginx
    type: landscaper.gardener.cloud/helm
    target:
      name: {{ .imports.target-cluster.metadata.name }}
      namespace: {{ .imports.target-cluster.metadata.namespace }}
    config:
      apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
      kind: ProviderConfiguration

      chart:
        ref: {{ with (getResource .cd "name" "ingress-nginx-chart") }}{{ .access.imageReference }}{{ end }}

      updateStrategy: patch

      name: ingress-nginx
      namespace: {{ .imports.nginx-namespace }}

      values:
        controller:
          livenessProbe:
            failureThreshold: 5
          readinessProbe:
            failureThreshold: 3
            initialDelaySeconds: 10
