#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -o errexit
set -o nounset
set -o pipefail

ABS_OUT_PATH=$(realpath $OUT_PATH)

cd "$(dirname $0)/.."

make install-requirements

mkdir -p /go/src/github.com/gardener/landscaper-cli
cp -r . /go/src/github.com/gardener/landscaper-cli
cd /go/src/github.com/gardener/landscaper-cli

make cross-build

mkdir -p $ABS_OUT_PATH
cp ./dist/*.gz "$ABS_OUT_PATH"
