#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"

ABS_OUT_PATH=$(realpath $OUT_PATH)

make cross-build

mkdir -p $ABS_OUT_PATH
cp ./dist/*.gz "$ABS_OUT_PATH"
