#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
if [[ -z ${LOCALBIN:-} ]]; then
  LOCALBIN="$PROJECT_ROOT/bin"
fi

"$PROJECT_ROOT/.ci/ensure-make"

# configure credentials
mkdir -p "$HOME/.docker"
gardener-ci docker cfg --image "europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper" > $HOME/.docker/config.json

(
  cd "${PROJECT_ROOT}"

  echo "Run 'make component-build' ..."
  make component-build
  echo "Component successfully built."

  echo "Run 'make component-push' ..."
  export OVERWRITE_COMPONENTS="true"
  make component-push
  echo "Component successfully pushed."
)
