#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
if [[ -z ${LOCALBIN:-} ]]; then
  LOCALBIN="$PROJECT_ROOT/bin"
fi

"$PROJECT_ROOT/.ci/ensure-make"

mkdir -p "$HOME/.docker"

(
  cd "${PROJECT_ROOT}"

  echo "Run 'make component-build' ..."
  make component-build
  echo "Component successfully built."

  echo "Run 'make component-push' ..."
  export OVERWRITE_COMPONENTS="true"
  gardener-ci docker cfg --image-ref-prefixes "europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper" > $HOME/.docker/config.json
  REGISTRY_PREFIX="europe-docker.pkg.dev/sap-gcp-cp-k8s-stable-hub/landscaper" make component-push
  gardener-ci docker cfg --image-ref-prefixes "eu.gcr.io/gardener-project/development" > $HOME/.docker/config.json
  REGISTRY_PREFIX="eu.gcr.io/gardener-project/development" make component-push
  echo "Component successfully pushed."
)
