#!/bin/sh

PROJECT_ROOT="$(dirname $0)/.."
LANDSCAPE="dev"
TARGET_CLUSTER=""

for i in "$@"
do
case $i in
        -target-clustername=*|--target-clustername=*)
        export TARGET_CLUSTER="${i#*=}"
        shift
    ;;
    *)
        # unknown option
        echo "Unkown option ${i#*=}"
        exit 1
    ;;
esac
done

if [[ $TARGET_CLUSTER == "" ]]; then
    echo "Required parameter: --target-clustername"
    exit 1
fi

if ! command -v python3 &> /dev/null
then
    echo "Python3 could not be found"
    echo "Try installing it..."
    apk add --no-cache --no-progress python3 python3-dev py3-pip gcc libc-dev libffi-dev openssl-dev cargo
fi

pip3 install --upgrade pip
pip3 install gardener-cicd-libs

${PROJECT_ROOT}/.ci/integration_test.py
