#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
source "$PROJECT_ROOT/.ci/ensure-go"
"$PROJECT_ROOT/.ci/ensure-make"

# Configure Go
export GOROOT="/usr/lib/go"
export GOPATH="/go"
export PATH="/go/bin:$PATH"

(
  cd "$PROJECT_ROOT"

  ccli_component_name="github.com/gardener/component-cli"

  if [[ "$DEPENDENCY_NAME" != "$ccli_component_name" ]]; then
    exit 0
  fi

  # get current version
  current_image_vector_component_version=$("$PROJECT_ROOT/hack/extract-module-version.sh" $ccli_component_name)

  if [[ "$image_vector_component_name" == "$DEPENDENCY_VERSION" ]]; then
    exit 0
  fi

  go get "${image_vector_component_name}@${DEPENDENCY_VERSION}"
  make revendor
)
