#!/bin/bash

# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

set -euo pipefail

PROJECT_ROOT="$(realpath $(dirname $0)/..)"
source "$PROJECT_ROOT/.ci/ensure-go"
"$PROJECT_ROOT/.ci/ensure-make"

(
  cd "${PROJECT_ROOT}"

  make verify
  make test
)
