# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: target-cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: nginx-namespace
      schema:
        type: string

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
  - name: ingress-nginx
    type: GoTemplate
    file: /ingress-nginx-execution.yaml
