# SPDX-FileCopyrightText: 2020 SAP SE or an SAP affiliate company and Gardener contributors
#
# SPDX-License-Identifier: Apache-2.0

apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
  - name: target-cluster
    targetType: landscaper.gardener.cloud/kubernetes-cluster
  - name: nginx-namespace
      schema:
        type: string

exports:
  - name: ingressClass
    schema:
      type: string
  - name: replicas
    schema:
      type: int

exportExecutions:
  - name: ingressClass
    type: GoTemplate
    template: |
      exports:
        ingressClass: {{ .values.deployitems.ingress-nginx.ingressClass }}
  - name: replicas
    type: GoTemplate
    template: |
      exports:
        replicas: {{ .values.deployitems.ingress-nginx.replicas }}

subinstallations: []

deployExecutions:
  - name: ingress-nginx
    type: GoTemplate
    template: |
      deployItems:
      - name: ingress-nginx
        type: landscaper.gardener.cloud/helm
        target:
          name: {{ .imports.target-cluster.metadata.name }}
          namespace: {{ .imports.target-cluster.metadata.namespace }}
        config:
          apiVersion: helm.deployer.landscaper.gardener.cloud/v1alpha1
          kind: ProviderConfiguration

          chart:
            ref: {{ with (getResource .cd "name" "ingress-nginx-chart") }}{{ .access.imageReference }}{{ end }}

          updateStrategy: patch

          name: ingress-nginx
          namespace: {{ .imports.nginx-namespace }}

          exportsFromManifests:
          - key: ingressClass
            jsonPath: .Values.controller.ingressClass
          - key: replicas
            jsonpath .spec.replicas
            apiVersion: apps/v1
            kind: deployment
            name: controller
            namespace: {{ .imports.nginx-namespace }}