apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Installation
metadata:
  name: echo-server-cd-example
  annotations:
    landscaper.gardener.cloud/operation: reconcile
spec:

  componentDescriptor:
    ref:
      repositoryContext:
        type: ociRegistry
        baseUrl: oci-registry.landscaper.svc.cluster.local:5000/components
      componentName: github.com/gardener/echo-server-cd
      version: v0.1.0

  blueprint:
    ref:
      resourceName: echo-server-blueprint

  imports:
    targets:
    - name: cluster
      target: "#test-target"
    
  importDataMappings:
    appname: echo-server
    appnamespace: landscaper-example
