apiVersion: landscaper.gardener.cloud/v1alpha1
kind: Blueprint

imports:
- default:
    value: null
  name: target-cluster
  required: true
  targetType: landscaper.gardener.cloud/kubernetes-cluster
- default:
    value: null
  name: nginx-namespace
  required: true
  schema:
    type: string
- default:
    value: null
  name: echo-server-namespace
  required: true
  schema:
    type: string
- default:
    value: null
  name: password-1
  required: true
  schema:
    type: string
- default:
    value: null
  name: password-2
  required: true
  schema:
    type: string

exports: []

exportExecutions: []

subinstallations: []

deployExecutions:
- file: /deploy-execution-nginx.yaml
  name: nginx
  type: GoTemplate
- file: /deploy-execution-echo.yaml
  name: echo
  type: GoTemplate
- file: /deploy-execution-secrets.yaml
  name: secrets
  type: GoTemplate
